@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "prog3#main(String[])",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "prog3",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_106940441 { 
   	label=prog3
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_524007932 { 
   	label=prog3
	labeljust=l
	fillcolor=white
	style=filled
   
   prog3106940441XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="prog3

null"
	penwidth=4
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_1281085568 { 
   	label=Passeger
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_726565422 { 
   	label=Passeger
	labeljust=l
	fillcolor=white
	style=filled
   
   Passeger1281085568XXXbreathe1841810700[
	label="+ breathe()"
	style=filled
	fillcolor=white
	tooltip="Passeger

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_380685548 { 
   	label=SmallRock
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_136726934 { 
   	label=SmallRock
	labeljust=l
	fillcolor=white
	style=filled
   
   SmallRock380685548XXXbeHarmed104431[
	label="+ beHarmed()"
	style=filled
	fillcolor=white
	tooltip="SmallRock

null"
	fontcolor=darkgreen
];

SmallRock380685548XXXbeThrownForDamage727088897[
	label="+ beThrownForDamage()"
	style=filled
	fillcolor=white
	tooltip="SmallRock

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_726803703 { 
   	label=Character
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_994218596 { 
   	label=Character
	labeljust=l
	fillcolor=white
	style=filled
   
   Character726803703XXXask726803703[
	label="+ ask()"
	style=filled
	fillcolor=white
	tooltip="Character

null"
	fontcolor=darkgreen
];

Character726803703XXXbeHarmed104431[
	label="+ beHarmed()"
	style=filled
	fillcolor=white
	tooltip="Character

null"
	fontcolor=darkgreen
];

Character726803703XXXbeThrownForDamage727088897[
	label="+ beThrownForDamage()"
	style=filled
	fillcolor=white
	tooltip="Character

null"
	fontcolor=darkgreen
];

Character726803703XXXgo1965687765[
	label="+ go()"
	style=filled
	fillcolor=white
	tooltip="Character

null"
	fontcolor=darkgreen
];

Character726803703XXXgo325210846[
	label="+ go()"
	style=filled
	fillcolor=white
	tooltip="Character

null"
	fontcolor=darkgreen
];

Character726803703XXXlookFor727088897[
	label="+ lookFor()"
	style=filled
	fillcolor=white
	tooltip="Character

null"
	fontcolor=darkgreen
];

Character726803703XXXpush726803703[
	label="+ push()"
	style=filled
	fillcolor=white
	tooltip="Character

null"
	fontcolor=darkgreen
];

Character726803703XXXseePeople1965687765[
	label="+ seePeople()"
	style=filled
	fillcolor=white
	tooltip="Character

null"
	fontcolor=darkgreen
];

Character726803703XXXshake726803703[
	label="+ shake()"
	style=filled
	fillcolor=white
	tooltip="Character

null"
	fontcolor=darkgreen
];

Character726803703XXXthrowForDamage1002426034[
	label="+ throwForDamage()"
	style=filled
	fillcolor=white
	tooltip="Character

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_77117080 { 
   	label=Pilot
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1669134398 { 
   	label=Pilot
	labeljust=l
	fillcolor=white
	style=filled
   
   Pilot77117080XXXSwitchOn851270936[
	label="+ SwitchOn()"
	style=filled
	fillcolor=white
	tooltip="Pilot

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_824025623 { 
   	label=InsideTheRocket
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_354176394 { 
   	label=Motor
	labeljust=l
	fillcolor=white
	style=filled
   
   Motor121106717XXXmotorOn431604156[
	label="+ motorOn()"
	style=filled
	fillcolor=white
	tooltip="Motor

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_851270936 { 
   	label=FictionRocket
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_485771874 { 
   	label=FictionRocket
	labeljust=l
	fillcolor=white
	style=filled
   
   FictionRocket851270936XXXSwitchOn77117080[
	label="+ SwitchOn()"
	style=filled
	fillcolor=white
	tooltip="FictionRocket

null"
	fontcolor=darkgreen
];

FictionRocket851270936XXXbeHarmed104431[
	label="+ beHarmed()"
	style=filled
	fillcolor=white
	tooltip="FictionRocket

null"
	fontcolor=darkgreen
];

FictionRocket851270936XXXbeThrownForDamage727088897[
	label="+ beThrownForDamage()"
	style=filled
	fillcolor=white
	tooltip="FictionRocket

null"
	fontcolor=darkgreen
];

FictionRocket851270936XXXcheckAirInRocket77117080[
	label="+ checkAirInRocket()"
	style=filled
	fillcolor=white
	tooltip="FictionRocket

null"
	fontcolor=darkgreen
];

FictionRocket851270936XXXfly1405293521[
	label="+ fly()"
	style=filled
	fillcolor=white
	tooltip="FictionRocket

null"
	fontcolor=darkgreen
];
} 
} 

'edges    
Character726803703XXXask726803703 -> Character726803703XXXgo1965687765;
Character726803703XXXask726803703 -> Character726803703XXXshake726803703;
Character726803703XXXshake726803703 -> Character726803703XXXgo1965687765;
Character726803703XXXshake726803703 -> Character726803703XXXpush726803703;
Character726803703XXXthrowForDamage1002426034 -> Character726803703XXXbeThrownForDamage727088897;
Character726803703XXXthrowForDamage1002426034 -> FictionRocket851270936XXXbeThrownForDamage727088897;
Character726803703XXXthrowForDamage1002426034 -> SmallRock380685548XXXbeThrownForDamage727088897;
FictionRocket851270936XXXSwitchOn77117080 -> Motor121106717XXXmotorOn431604156;
FictionRocket851270936XXXcheckAirInRocket77117080 -> Passeger1281085568XXXbreathe1841810700;
FictionRocket851270936XXXfly1405293521 -> Character726803703XXXgo1965687765;
Pilot77117080XXXSwitchOn851270936 -> FictionRocket851270936XXXSwitchOn77117080;
SmallRock380685548XXXbeThrownForDamage727088897 -> Character726803703XXXbeHarmed104431;
SmallRock380685548XXXbeThrownForDamage727088897 -> FictionRocket851270936XXXbeHarmed104431;
SmallRock380685548XXXbeThrownForDamage727088897 -> SmallRock380685548XXXbeHarmed104431;
prog3106940441XXXmain1859653459 -> Character726803703XXXask726803703;
prog3106940441XXXmain1859653459 -> Character726803703XXXgo1965687765;
prog3106940441XXXmain1859653459 -> Character726803703XXXgo325210846;
prog3106940441XXXmain1859653459 -> Character726803703XXXlookFor727088897;
prog3106940441XXXmain1859653459 -> Character726803703XXXseePeople1965687765;
prog3106940441XXXmain1859653459 -> Character726803703XXXshake726803703;
prog3106940441XXXmain1859653459 -> Character726803703XXXthrowForDamage1002426034;
prog3106940441XXXmain1859653459 -> FictionRocket851270936XXXcheckAirInRocket77117080;
prog3106940441XXXmain1859653459 -> FictionRocket851270936XXXfly1405293521;
prog3106940441XXXmain1859653459 -> Pilot77117080XXXSwitchOn851270936;
    
}
@enduml